server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/security?serverTimezone=Asia/Seoul
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  # OAuth2 설정
  # security.oauth2.client.registration 을 사용하면
  # spring.security.oauth2.client.registration 을 사용하지 않아도 된다.
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # 구글 클라이언트 ID
            client-secret: # 구글 클라이언트 시크릿
            scope:
              - email
              - profile